### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by rapilabs** [syrusakbary/graphql-relay-py#1]
Trying to run on python 3.4.3... am hitting errors with base64 encoding:

Getting a GraphQLError with no traceback, just a single line: "'str' does not support the buffer interface"

Traced the error to https://github.com/syrusakbary/graphql-relay-py/blob/master/graphql_relay/node/node.py#L66

**Comment by syrusakbary** [comment]
Python 3 is now supported!
Please update the package with `pip install graphql-relay>=0.1.2` :)

**Comment by rapilabs** [comment]
Thanks! :)
